#!/bin/bash

set -ex

if [ ! -f /usr/bin/docker ]
then
    echo Error: please apt install docker.io >&2
    exit 2
fi

cd "$(dirname $0)"

docker build -t skyfield-python-2.6 . 1>&2

#     -v $PWD/../../../assay:/assay \
exec docker run -ti \
     -v $PWD/../..:/skyfield \
     skyfield-python-2.6 "$@"
